# CMake generated Testfile for 
# Source directory: E:/android/AiAssist/app/src/main/cpp/cJSON/tests
# Build directory: E:/android/AiAssist/app/src/main/cpp/cJSON/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_examples "./parse_examples")
  set_tests_properties(parse_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_examples "./parse_examples")
  set_tests_properties(parse_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_examples "./parse_examples")
  set_tests_properties(parse_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_examples "./parse_examples")
  set_tests_properties(parse_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_examples NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_number "./parse_number")
  set_tests_properties(parse_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_number "./parse_number")
  set_tests_properties(parse_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_number "./parse_number")
  set_tests_properties(parse_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_number "./parse_number")
  set_tests_properties(parse_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_number NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_hex4 "./parse_hex4")
  set_tests_properties(parse_hex4 PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_hex4 "./parse_hex4")
  set_tests_properties(parse_hex4 PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_hex4 "./parse_hex4")
  set_tests_properties(parse_hex4 PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_hex4 "./parse_hex4")
  set_tests_properties(parse_hex4 PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_hex4 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_string "./parse_string")
  set_tests_properties(parse_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_string "./parse_string")
  set_tests_properties(parse_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_string "./parse_string")
  set_tests_properties(parse_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_string "./parse_string")
  set_tests_properties(parse_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_string NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_array "./parse_array")
  set_tests_properties(parse_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_array "./parse_array")
  set_tests_properties(parse_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_array "./parse_array")
  set_tests_properties(parse_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_array "./parse_array")
  set_tests_properties(parse_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_array NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_object "./parse_object")
  set_tests_properties(parse_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_object "./parse_object")
  set_tests_properties(parse_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_object "./parse_object")
  set_tests_properties(parse_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_object "./parse_object")
  set_tests_properties(parse_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_object NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_value "./parse_value")
  set_tests_properties(parse_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_value "./parse_value")
  set_tests_properties(parse_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_value "./parse_value")
  set_tests_properties(parse_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_value "./parse_value")
  set_tests_properties(parse_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_value NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(print_string "./print_string")
  set_tests_properties(print_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(print_string "./print_string")
  set_tests_properties(print_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(print_string "./print_string")
  set_tests_properties(print_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(print_string "./print_string")
  set_tests_properties(print_string PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(print_string NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(print_number "./print_number")
  set_tests_properties(print_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(print_number "./print_number")
  set_tests_properties(print_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(print_number "./print_number")
  set_tests_properties(print_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(print_number "./print_number")
  set_tests_properties(print_number PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(print_number NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(print_array "./print_array")
  set_tests_properties(print_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(print_array "./print_array")
  set_tests_properties(print_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(print_array "./print_array")
  set_tests_properties(print_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(print_array "./print_array")
  set_tests_properties(print_array PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(print_array NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(print_object "./print_object")
  set_tests_properties(print_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(print_object "./print_object")
  set_tests_properties(print_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(print_object "./print_object")
  set_tests_properties(print_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(print_object "./print_object")
  set_tests_properties(print_object PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(print_object NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(print_value "./print_value")
  set_tests_properties(print_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(print_value "./print_value")
  set_tests_properties(print_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(print_value "./print_value")
  set_tests_properties(print_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(print_value "./print_value")
  set_tests_properties(print_value PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(print_value NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(misc_tests "./misc_tests")
  set_tests_properties(misc_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(misc_tests "./misc_tests")
  set_tests_properties(misc_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(misc_tests "./misc_tests")
  set_tests_properties(misc_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(misc_tests "./misc_tests")
  set_tests_properties(misc_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(misc_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(parse_with_opts "./parse_with_opts")
  set_tests_properties(parse_with_opts PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(parse_with_opts "./parse_with_opts")
  set_tests_properties(parse_with_opts PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(parse_with_opts "./parse_with_opts")
  set_tests_properties(parse_with_opts PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(parse_with_opts "./parse_with_opts")
  set_tests_properties(parse_with_opts PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(parse_with_opts NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(compare_tests "./compare_tests")
  set_tests_properties(compare_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(compare_tests "./compare_tests")
  set_tests_properties(compare_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(compare_tests "./compare_tests")
  set_tests_properties(compare_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(compare_tests "./compare_tests")
  set_tests_properties(compare_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(compare_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cjson_add "./cjson_add")
  set_tests_properties(cjson_add PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cjson_add "./cjson_add")
  set_tests_properties(cjson_add PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cjson_add "./cjson_add")
  set_tests_properties(cjson_add PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cjson_add "./cjson_add")
  set_tests_properties(cjson_add PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(cjson_add NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(readme_examples "./readme_examples")
  set_tests_properties(readme_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(readme_examples "./readme_examples")
  set_tests_properties(readme_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(readme_examples "./readme_examples")
  set_tests_properties(readme_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(readme_examples "./readme_examples")
  set_tests_properties(readme_examples PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(readme_examples NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(minify_tests "./minify_tests")
  set_tests_properties(minify_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(minify_tests "./minify_tests")
  set_tests_properties(minify_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(minify_tests "./minify_tests")
  set_tests_properties(minify_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(minify_tests "./minify_tests")
  set_tests_properties(minify_tests PROPERTIES  _BACKTRACE_TRIPLES "E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;84;add_test;E:/android/AiAssist/app/src/main/cpp/cJSON/tests/CMakeLists.txt;0;")
else()
  add_test(minify_tests NOT_AVAILABLE)
endif()
