/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.4-91-g5507a40624"
#endif /* AVUTIL_FFVERSION_H */
